import Head from 'next/head';

export default function Submit() {
  return (
    <div className="px-4 py-4">
      <Head>
        <title>Wailuku Walking Tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="min-h-full flex flex-col">
        <h1 className="text-3xl text-primary text-center font-bold mt-3">Community Stories</h1>
        <p className="font-light mt-2">Share your unique perspective, family history, or personal experience with this place!</p>
        <p className="font-light mt-2">Record or write your story below</p>
        <button className="btn btn-info mt-4">Submit</button>
      </div>
    </div>
  )
}
